// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:slug": {
    params: {
      "slug": string;
    };
  };
  "/tags/:tag": {
    params: {
      "tag": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:slug" | "/tags/:tag";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$slug.tsx": {
    id: "routes/$slug";
    page: "/:slug";
  };
  "routes/tags.$tag.tsx": {
    id: "routes/tags.$tag";
    page: "/tags/:tag";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$slug": typeof import("./app/routes/$slug.tsx");
  "routes/tags.$tag": typeof import("./app/routes/tags.$tag.tsx");
};